apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops-team
  description: Time de DevOps responsável pelos serviços do portal.
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jandradevtg
spec:
  memberOf:
    - devops-team
